---
title: "TrueExperiment"
author: "Alex Bieniek"
date: "March 4, 2019"
output: pdf_document
---

## Motivation
  Students, researchers, and most people beyond these buckets believe that caffeine improves their productivity. Many even insist on having their morning coffee to do their work each day. We design an experiment to empirically evaluate the effects of caffeine as well as other intake trends on one's mental acuity.
  Perhaps caffeine truly improves one's performance in their studies or work. However, we may also investigate the existence of a placebo effect on one's work ethic. We also investigate more complex effects of caffeine with its relationship on mental acuity, such as the influence of the caffeine-induced "crash", and caffeine tolerance, and possible relationships between caffeine effectiveness and amount of sleep.
  
## Theory


## Research Questions
Put succinctly, here are some of the questions that we investigate in this experiment:
- Does caffeine intake change one's mental acuity?
- Does the "caffeine crash", or the perceived exhaustion after wearing off of caffeine, change one's mental acuity?
- Does there exist a placebo affect in caffeine intake and one's mental acuity?
- Does caffeine tolerance change the effectiveness of a single dose of caffeine?
- Does one's recent amount of sleep change the effectiveness of caffeine at changing one's mental acuity?

## Participants
  For convenience and consistency, the experiment will use students from TUDelft as participants. A sample from this population would likely generalize to broader student populations for the effects of caffeine intake. We can also find various levels of caffeine intake habits and regular sleep amounts. Lastly, because the students belong to the same university, we can expect that, with a lower variance in mental acuity, a smaller sample size could suffice for testing of statistical significance.
  One thing to consider is that, because TUDelft is a linguistically diverse university, we can make no assumptions about the language backgrounds of the students. As such, it is important to test subjects with means independent of reading ability, domain experience, etc.
  Administering of caffeine shall be transparent and consentual. Caffeine will be administered in commercially available forms and otherwise ordinary forms, with the possibility of caffeine-free doses.

## Conceptual Model
**Dependent Variable: reading test score**
Mental acuity is difficult to measure, so we will approximate it by administering a brief intelligence examination. In particular, the subject will be given an IQ test, which can be used as an unbiased approximation of the mentual acuity of a subject.

**Independent Variables:**  
* Amount of Administered Caffeine (in mg)  
* Duration Since Caffeine Dose  
 
**Mediating Variables:**  
* Caffeine Tolerance (as approximated by amount of caffeine per day)  
* Average Sleep Amount (in Hours)  
 
**Moderating Variables:**  
* Percieved Inake of Caffeine  (Placebo or No Placebo)
 
## Experimental Design
The experiment explores the change in mental accuity as described by various factors around caffeine intake. There are many variables which many complicate and influence the change in mental accuity, such as caffeine tolerance and duration since dose, and these variables will be tested in experiments where other variables are controlled.

## Experimental Procedure
For the colection of data from test subjects:  
1. Randomly sample a test subject from a place of study, and preemptively, randomly assign treatment to the subject  
 * treatment would be in the form of a dose of caffeine, a placebo dose of caffeine, or no dose of caffeine  
 * We would need to find people who have not had any caffeine yet on the given day  
2. Collect some preliminary information about the subject, including estimated sleep amount and estimated caffeine intake per day  
3. administer a waiting period for the subject to go about other activities and allow the caffeine to kick in and/or wear off  
 * Duration of waiting period will be influenced by academic literature about caffeine  
4. After the waiting period, administer the IQ test  
 * The test should be realistically impossible to complete in the given amount of time to avoid statistically   meaningless score distributions  


## Experiments and Suggested Statistical Analyses
In this section, we describe the types of independent variables that we will observe and what statistical tests would allow for hypothesis testing:  
1. Effect of Caffeine Intake on Mental Accuity -> two-sample t-statistic  
2. Placebo Effect of Caffeine Intake -> two-sample t-statistic  
2. Effectiveness of Caffeine Intake Over Time -> Regression Analysis  
3. Influence of Caffeine Tolerance on Caffeine Effectiveness -> Regression Analysis  
3. Influence of Sleep on Caffeine Effectiveness -> Multiple Regression Analysis  